// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckAuth() {
  return window['go']['main']['App']['CheckAuth']();
}

export function GetLocation() {
  return window['go']['main']['App']['GetLocation']();
}

export function GetRegisteredCharacters() {
  return window['go']['main']['App']['GetRegisteredCharacters']();
}

export function GetZkill(arg1) {
  return window['go']['main']['App']['GetZkill'](arg1);
}

export function LogOut() {
  return window['go']['main']['App']['LogOut']();
}

export function OpenAuth() {
  return window['go']['main']['App']['OpenAuth']();
}

export function SwitchCurrentCharacter(arg1) {
  return window['go']['main']['App']['SwitchCurrentCharacter'](arg1);
}
